export const SET_COMPARE_PLAYERS_ID = 'SET_COMPARE_PLAYERS_ID';

export const SET_ALL_PLAYERS = 'SET_ALL_PLAYERS';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_HIGHLIGHT_WL = 'SET_HIGHLIGHT_WL';
export const SET_MIN_INDEX = 'SET_MIN_INDEX';
export const SET_MISSING_FIELDS = 'SET_MISSING_FIELDS';
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const SET_PLAYER_BIO = 'SET_PLAYER_BIO';
export const SET_PLAYER_CUMULATIVE_AVERAGE_GAME_LOG = 'SET_PLAYER_CUMULATIVE_AVERAGE_GAME_LOG';
export const SET_PLAYER_CUMULATIVE_TOTAL_GAME_LOG = 'SET_PLAYER_CUMULATIVE_TOTAL_GAME_LOG';
export const SET_PLAYER_GAME_LOG = 'SET_PLAYER_GAME_LOG';
export const SET_PLAYER_ID = 'SET_PLAYER_ID';

export const SET_CHOSEN_LETTER = 'SET_CHOSEN_LETTER';
export const SET_PLAYER_ERROR = 'SET_PLAYER_ERROR';
