export const SET_ALL_PLAYERS = 'SET_ALL_PLAYERS';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const SET_PLAYER_BIO = 'SET_PLAYER_BIO';
export const SET_PLAYER_CUMULATIVE_AVERAGE_GAME_LOG = 'SET_PLAYER_CUMULATIVE_AVERAGE_GAME_LOG';
export const SET_PLAYER_CUMULATIVE_TOTAL_GAME_LOG = 'SET_PLAYER_CUMULATIVE_TOTAL_GAME_LOG';
export const SET_PLAYER_GAME_LOG = 'SET_PLAYER_GAME_LOG';
export const SET_PLAYER_ID = 'SET_PLAYER_ID';
